version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PORT=8080
    volumes:
      - .:/app
    restart: unless-stopped
